# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLogin():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_login(self):
    #переходим на сайт
    self.driver.get("http://www.motka-freshdoc.qds.ru/")
    self.driver.set_window_size(1280, 984)
    # процесс верефикации
    self.driver.find_element(By.LINK_TEXT, "Войти").click()
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("test.qds.777@bk.ru")
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys("AnSa1991")
    self.driver.find_element(By.CSS_SELECTOR, ".button:nth-child(3)").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".qd-filelist-table-item:nth-child(3) .qd-filelist-table-item__field_\\418\\43C\\44F")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".qd-filelist-table-item:nth-child(3) .qd-filelist-table-item__field_\\418\\43C\\44F")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".qd-filelist-table-item:nth-child(3) .qd-filelist-table-item__field_\\418\\43C\\44F").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".qd-icon_create-file").click()
    self.driver.find_element(By.CSS_SELECTOR, ".qd-filelist-table-item:nth-child(6) .qd-filelist-table-item__field_\\418\\43C\\44F").click()
    self.driver.find_element(By.CSS_SELECTOR, ".qd-catalog-dialog__button_confirm > .qd-catalog-dialog-button__caption").click()
    self.driver.find_element(By.CSS_SELECTOR, ".qd-filelist-table-item:nth-child(5) .qd-filelist-table-item__field_\\41D\\430\\438\\43C\\435\\43D\\43E\\432\\430\\43D\\438\\435").click()
    self.driver.find_element(By.ID, "E321B633-A0D4-4346-9F9F-79686BE31F62").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".qd-edit-field")
    self.driver.execute_script("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '1000'}", element)
    self.driver.find_element(By.ID, "BE67E8F5-3C35-4EA0-89A1-BB5ADF130FF6").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".qd-edit-field")
    self.driver.execute_script("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = 'Уфа'}", element)
    self.driver.find_element(By.ID, "627B631C-2AFA-452C-943A-4E76E746AA38").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".qd-edit-field")
    self.driver.execute_script("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '12122000'}", element)
    self.driver.find_element(By.CSS_SELECTOR, ".qd-carcass-btn-save").click()
    self.driver.find_element(By.CSS_SELECTOR, ".qd-control-menuitem:nth-child(1) > .qd-control-menuitem-caption").click()
    self.driver.find_element(By.CSS_SELECTOR, ".qd-icon_close").click()
    self.driver.find_element(By.LINK_TEXT, "test.qds.777@bk.ru").click()
    self.driver.find_element(By.CSS_SELECTOR, ".qd-button_auth > .DD-button__caption").click()
    self.driver.find_element(By.CSS_SELECTOR, ".qd-global-button").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".qd-filelist-table-item:nth-child(11) .qd-filelist-table-item__field_\\418\\43C\\44F")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
  
